# Generated by Django 5.0 on 2024-12-02 01:16

import core.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='goal',
            name='core_goal_user_id_09445c_idx',
        ),
        migrations.RemoveIndex(
            model_name='goal',
            name='core_goal_deadlin_dc7eee_idx',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='progress',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='required_level',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='xp_reward',
        ),
        migrations.AddField(
            model_name='goal',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='priority',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='goal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='quest',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quests', to='core.goal'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='goal_type',
            field=models.CharField(choices=[('personal', 'Personal Development'), ('career', 'Career'), ('health', 'Health & Fitness'), ('education', 'Education'), ('financial', 'Financial'), ('creative', 'Creative'), ('social', 'Social'), ('other', 'Other')], default='personal', max_length=20),
        ),
        migrations.AlterField(
            model_name='quest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='quest',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quest',
            name='difficulty',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='quest',
            name='required_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='quest',
            name='reward_coins',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='quest',
            name='reward_xp',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='quest',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='not_started', max_length=20),
        ),
        migrations.AlterField(
            model_name='quest',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='coins',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='personality_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='rank',
            field=models.CharField(choices=[('F', 'F-Rank Hunter'), ('E', 'E-Rank Hunter'), ('D', 'D-Rank Hunter'), ('C', 'C-Rank Hunter'), ('B', 'B-Rank Hunter'), ('A', 'A-Rank Hunter'), ('S', 'S-Rank Hunter')], default='F', max_length=1, validators=[core.models.validate_rank]),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['user', 'deadline'], name='core_goal_user_id_542e8c_idx'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['user', 'is_active'], name='core_goal_user_id_ec9594_idx'),
        ),
    ]
