# Generated by Django 5.0 on 2024-12-02 01:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_goal_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='quest',
            name='core_quest_difficu_884e0d_idx',
        ),
        migrations.RemoveIndex(
            model_name='quest',
            name='core_quest_require_2f90a8_idx',
        ),
        migrations.RemoveIndex(
            model_name='quest',
            name='core_quest_created_27552a_idx',
        ),
        migrations.RemoveIndex(
            model_name='quest',
            name='core_quest_status_19db7a_idx',
        ),
        migrations.AddField(
            model_name='quest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='quest',
            index=models.Index(fields=['user', 'status'], name='core_quest_user_id_fc77fe_idx'),
        ),
        migrations.AddIndex(
            model_name='quest',
            index=models.Index(fields=['goal', 'status'], name='core_quest_goal_id_24d26b_idx'),
        ),
        migrations.AddIndex(
            model_name='quest',
            index=models.Index(fields=['completed_at'], name='core_quest_complet_615771_idx'),
        ),
    ]
