# Generated by Django 5.0 on 2024-12-02 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_quest_core_quest_difficu_884e0d_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'EASY'), (2, 'MEDIUM'), (3, 'HARD'), (4, 'EXPERT'), (5, 'LEGENDARY')], default=1, help_text='Quest difficulty level'),
        ),
    ]
