# Generated by Django 5.0 on 2024-12-02 01:30

from django.db import migrations


def convert_difficulty_to_int(apps, schema_editor):
    Quest = apps.get_model('core', 'Quest')
    
    difficulty_map = {
        'EASY': 1,
        'MEDIUM': 2,
        'HARD': 3,
        'EXPERT': 4,
        'LEGENDARY': 5
    }
    
    # Update all quests with string difficulties to their integer equivalents
    for quest in Quest.objects.all():
        if isinstance(quest.difficulty, str):
            quest.difficulty = difficulty_map.get(quest.difficulty.upper(), 1)  # Default to EASY if unknown
            quest.save()

def reverse_difficulty_conversion(apps, schema_editor):
    Quest = apps.get_model('core', 'Quest')
    
    difficulty_map = {
        1: 'EASY',
        2: 'MEDIUM',
        3: 'HARD',
        4: 'EXPERT',
        5: 'LEGENDARY'
    }
    
    # Revert all quests back to string difficulties
    for quest in Quest.objects.all():
        if isinstance(quest.difficulty, int):
            quest.difficulty = difficulty_map.get(quest.difficulty, 'EASY')  # Default to EASY if unknown
            quest.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_quest_difficulty'),
    ]

    operations = [
        migrations.RunPython(
            convert_difficulty_to_int,
            reverse_difficulty_conversion
        ),
    ]
