# Generated by Django 5.0 on 2024-12-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_userprofile_agility_userprofile_intelligence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='icon',
            field=models.CharField(default='box', max_length=50),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='rarity',
            field=models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='common', max_length=20),
        ),
        migrations.AddIndex(
            model_name='shopitem',
            index=models.Index(fields=['item_type'], name='core_shopit_item_ty_a20204_idx'),
        ),
        migrations.AddIndex(
            model_name='shopitem',
            index=models.Index(fields=['rarity'], name='core_shopit_rarity_4ffefe_idx'),
        ),
    ]
