# Generated by Django 5.0 on 2024-12-02 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_shopitem_icon_shopitem_rarity_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='shopitem',
            name='core_shopit_item_ty_a20204_idx',
        ),
        migrations.RemoveIndex(
            model_name='shopitem',
            name='core_shopit_rarity_4ffefe_idx',
        ),
        migrations.RemoveField(
            model_name='shopitem',
            name='effect',
        ),
        migrations.AddField(
            model_name='quest',
            name='quest_type',
            field=models.CharField(choices=[('strength', 'Strength'), ('agility', 'Agility'), ('vitality', 'Vitality'), ('sense', 'Sense'), ('intelligence', 'Intelligence'), ('general', 'General')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='stat_increase',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='stat_type',
            field=models.CharField(blank=True, choices=[('strength', 'Strength'), ('agility', 'Agility'), ('vitality', 'Vitality'), ('sense', 'Sense'), ('intelligence', 'Intelligence')], max_length=20, null=True),
        ),
    ]
