# Generated by Django 5.0 on 2024-12-02 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_shopitem_core_shopit_item_ty_a20204_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='notification_preferences',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='strengths',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weaknesses',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
