# Generated by Django 5.0 on 2024-12-02 21:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_userprofile_notification_preferences_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='category',
            field=models.CharField(choices=[('personal', 'Personal Development'), ('career', 'Career'), ('health', 'Health & Fitness'), ('education', 'Education'), ('financial', 'Financial'), ('creative', 'Creative'), ('social', 'Social'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='item_type',
            field=models.CharField(choices=[('EQUIPMENT', 'Equipment'), ('CONSUMABLE', 'Consumable')], default='EQUIPMENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='price',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='rarity',
            field=models.CharField(choices=[('COMMON', 'Common'), ('UNCOMMON', 'Uncommon'), ('RARE', 'Rare'), ('EPIC', 'Epic'), ('LEGENDARY', 'Legendary')], default='COMMON', max_length=20),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='stat_increase',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='stat_type',
            field=models.CharField(choices=[('strength', 'Strength'), ('agility', 'Agility'), ('vitality', 'Vitality'), ('sense', 'Sense'), ('intelligence', 'Intelligence')], default='strength', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='coins',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='daily_quest_limit',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='inventory',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
